# Generated by Django 4.1 on 2023-09-01 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="School",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250, verbose_name="School Name")),
                (
                    "principal",
                    models.CharField(max_length=100, verbose_name="School Principal"),
                ),
                (
                    "location",
                    models.CharField(max_length=50, verbose_name="School Location "),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250, verbose_name="Student Name")),
                ("age", models.PositiveIntegerField(verbose_name="Student Age")),
                (
                    "School",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="students",
                        to="schDetails.school",
                        verbose_name="Student School",
                    ),
                ),
            ],
        ),
    ]
