# Generated by Django 4.1 on 2023-09-03 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schDetails", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="profile_pic",
            field=models.ImageField(blank=True, upload_to="profile_pic"),
        ),
    ]
