# Generated by Django 4.1 on 2023-09-05 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schDetails", "0002_student_profile_pic"),
    ]

    operations = [
        migrations.CreateModel(
            name="Hotel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("hotel_Main_Img", models.ImageField(upload_to="images/")),
            ],
        ),
    ]
