# Generated by Django 4.1 on 2023-09-06 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schDetails", "0003_hotel"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Hotel",
        ),
        migrations.AlterField(
            model_name="student",
            name="profile_pic",
            field=models.ImageField(blank=True, upload_to="images/student_profile_pic"),
        ),
    ]
